/* Merge PDF: all document work happens locally in the browser. */
(function () {
  "use strict";
  const { PDFDocument } = window.PDFLib;
  let files = [];
  const $ = (id) => document.getElementById(id);
  const dropzone = $("dropzone"), fileInput = $("fileInput"), fileListEl = $("fileList"), mergeBtn = $("mergeBtn"), clearBtn = $("clearBtn"), statusEl = $("status"), emptyQueue = $("emptyQueue"), fileCount = $("fileCount"), statsFiles = $("statsFiles"), statsSize = $("statsSize"), filenameInput = $("filenameInput"), cameraPanel = $("cameraPanel"), cameraPreview = $("cameraPreview"), cameraCanvas = $("cameraCanvas"), captureBtn = $("captureBtn");
  let cameraStream = null;
  const kindOf = (file) => { const name = file.name.toLowerCase(); if (file.type === "application/pdf" || name.endsWith(".pdf")) return "pdf"; if (file.type === "image/jpeg" || file.type === "image/png" || /\.(jpe?g|png)$/.test(name)) return "image"; return null; };
  function addFiles(list) { const all = Array.from(list), accepted = all.filter((file) => kindOf(file)); files = files.concat(accepted); render(); setStatus(all.length === accepted.length ? "" : `Skipped ${all.length - accepted.length} unsupported file(s). Use PDF, JPEG, or PNG.`, all.length === accepted.length ? "" : "error"); }
  $("browseBtn").addEventListener("click", (event) => { event.stopPropagation(); fileInput.click(); }); $("cameraBtn").addEventListener("click", (event) => { event.stopPropagation(); openCamera(); });
  dropzone.addEventListener("click", (event) => { if (!event.target.closest("button")) fileInput.click(); }); dropzone.addEventListener("keydown", (event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); fileInput.click(); } });
  fileInput.addEventListener("change", () => { addFiles(fileInput.files); fileInput.value = ""; });
  ["dragenter", "dragover"].forEach((type) => dropzone.addEventListener(type, (event) => { event.preventDefault(); dropzone.classList.add("dropzone--dragover"); })); ["dragleave", "drop"].forEach((type) => dropzone.addEventListener(type, (event) => { event.preventDefault(); dropzone.classList.remove("dropzone--dragover"); })); dropzone.addEventListener("drop", (event) => addFiles(event.dataTransfer.files));
  async function openCamera() { if (!navigator.mediaDevices?.getUserMedia) { setStatus("This browser does not support in-page camera capture.", "error"); return; } try { closeCamera(); cameraStream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: { ideal: "environment" } }, audio: false }); cameraPreview.srcObject = cameraStream; cameraPanel.hidden = false; await cameraPreview.play(); setStatus("Camera ready. Frame your photo, then capture it."); } catch (error) { console.error(error); setStatus("Camera access was not available. Allow camera permission and try again.", "error"); } }
  function closeCamera() { if (cameraStream) cameraStream.getTracks().forEach((track) => track.stop()); cameraStream = null; cameraPreview.srcObject = null; cameraPanel.hidden = true; }
  captureBtn.addEventListener("click", () => { if (!cameraPreview.videoWidth || !cameraPreview.videoHeight) return; cameraCanvas.width = cameraPreview.videoWidth; cameraCanvas.height = cameraPreview.videoHeight; cameraCanvas.getContext("2d").drawImage(cameraPreview, 0, 0); cameraCanvas.toBlob((blob) => { if (!blob) { setStatus("The photo could not be captured. Please try again.", "error"); return; } const stamp = new Date().toISOString().replace(/[:.]/g, "-"); addFiles([new File([blob], `camera-${stamp}.jpg`, { type: "image/jpeg" })]); closeCamera(); setStatus("Photo added to the merge queue.", "success"); }, "image/jpeg", 0.92); });
  ["closeCameraBtn", "cancelCameraBtn"].forEach((id) => $(id).addEventListener("click", () => { closeCamera(); setStatus(""); })); window.addEventListener("pagehide", closeCamera);
  function move(index, delta) { const target = index + delta; if (target < 0 || target >= files.length) return; [files[index], files[target]] = [files[target], files[index]]; render(); }
  function render() { fileListEl.innerHTML = ""; const count = files.length, total = files.reduce((sum, file) => sum + file.size, 0); fileCount.textContent = count ? `${count} file${count === 1 ? "" : "s"} · order matters` : "No files yet"; statsFiles.textContent = count; statsSize.textContent = count ? formatSize(total) : "—"; emptyQueue.hidden = count > 0; files.forEach((file, index) => { const li = document.createElement("li"); li.className = "file-item"; const label = kindOf(file) === "image" ? "Photo" : "PDF"; li.innerHTML = `<span class="file-item__index">${String(index + 1).padStart(2, "0")}</span><span class="file-item__name" title="${escapeHtml(file.name)}">${escapeHtml(file.name)}</span><span class="file-item__meta">${label} · ${formatSize(file.size)}</span><span class="file-item__controls"><button type="button" class="btn btn--icon" data-act="up" ${index === 0 ? "disabled" : ""} aria-label="Move ${escapeHtml(file.name)} earlier">↑</button><button type="button" class="btn btn--icon" data-act="down" ${index === count - 1 ? "disabled" : ""} aria-label="Move ${escapeHtml(file.name)} later">↓</button><button type="button" class="btn btn--icon" data-act="remove" aria-label="Remove ${escapeHtml(file.name)}">×</button></span>`; li.querySelector('[data-act="up"]').addEventListener("click", () => move(index, -1)); li.querySelector('[data-act="down"]').addEventListener("click", () => move(index, 1)); li.querySelector('[data-act="remove"]').addEventListener("click", () => { files.splice(index, 1); render(); }); fileListEl.appendChild(li); }); mergeBtn.disabled = count < 2; clearBtn.disabled = count === 0; }
  clearBtn.addEventListener("click", () => { files = []; render(); setStatus(""); });
  mergeBtn.addEventListener("click", async () => { if (files.length < 2) return; setBusy(true); setStatus("Creating your combined PDF…"); try { const merged = await PDFDocument.create(); for (const file of files) { const bytes = await file.arrayBuffer(); if (kindOf(file) === "image") { const image = /\.png$/i.test(file.name) || file.type === "image/png" ? await merged.embedPng(bytes) : await merged.embedJpg(bytes); const page = merged.addPage([image.width, image.height]); page.drawImage(image, { x: 0, y: 0, width: image.width, height: image.height }); } else { const source = await PDFDocument.load(bytes); const pages = await merged.copyPages(source, source.getPageIndices()); pages.forEach((page) => merged.addPage(page)); } } const cleanName = filenameInput.value.trim().replace(/[\\/:*?"<>|]/g, "-") || "merged"; download(await merged.save(), `${cleanName}.pdf`); setStatus(`Your combined PDF is ready: ${cleanName}.pdf`, "success"); } catch (error) { console.error(error); setStatus("One of those files could not be merged. Check that each PDF is valid and try again.", "error"); } finally { setBusy(false); } });
  function setBusy(busy) { mergeBtn.disabled = busy || files.length < 2; clearBtn.disabled = busy || !files.length; mergeBtn.firstChild.textContent = busy ? "Merging… " : "Merge & download "; }
  function setStatus(message, type) { statusEl.textContent = message; statusEl.className = `status${type ? ` status--${type}` : ""}`; } function download(bytes, name) { const url = URL.createObjectURL(new Blob([bytes], { type: "application/pdf" })); const link = document.createElement("a"); link.href = url; link.download = name; link.click(); URL.revokeObjectURL(url); } function formatSize(bytes) { return bytes < 1024 * 1024 ? `${Math.max(.1, bytes / 1024).toFixed(1)} KB` : `${(bytes / (1024 * 1024)).toFixed(1)} MB`; } function escapeHtml(value) { return value.replace(/[&<>"']/g, (char) => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", '"':"&quot;", "'":"&#39;" }[char])); }
  render();
})();
